package com.tonic.services.ClickPacket;

public enum PacketInteractionType {
    ACTION_PACKET_INTERACT,
    BANK_INTERACT,
    BANK_INVENTORY_INTERACT,
    EQUIPMENTITEM_INTERACT,
    INVENTORY_INTERACT,
    MOVEMENT_INTERACT,
    NPC_INTERACT,
    PLAYER_INTERACT,
    PRAYER_INTERACT,
    TILEITEM_INTERACT,
    TILEOBJECT_INTERACT,
    WIDGET_ON_TILEOBJECT_INTERACT,
    WIDGET_ON_WIDGET_INTERACT,
    WIDGET_INTERACT,
    UNBOUND_INTERACT
}
